name: Commit Now

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email'
        required: true
        default: 'rakkaevandra@gmail.com'
      username:
        description: 'Username'
        required: true
        default: 'RakkaEvandra06'
      commit:
        description: 'Commit'
        required: true
        default: 'Penghijauan'
      limit:
        description: 'Limit Commit'
        required: true
        default: '5'

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set Config & First Commit
        run: |
          git config user.email "${{ github.event.inputs.email }}"
          git config user.name "${{ github.event.inputs.username }}"

      - name: Perform sequential commits
        run: |
          LIMIT=${{ github.event.inputs.limit }}

          for ((i=1; i<=LIMIT; i++))
          do
            echo "$i-$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > LAST_UPDATED

            git add -A
            git commit -m "${{ github.event.inputs.commit }}" || true
          done

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true