name: Commit Now

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email'
        required: true
        default: 'rakkaevandra@gmail.com'
      username:
        description: 'Username'
        required: true
        default: 'RakkaEvandra06'
      commit:
        description: 'Commit'
        required: true
        default: 'Penghijauan'
      limit:
        description: 'Limit Commit'
        required: true
        default: '5'

  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set Config & First Commit
        run: |
          git config user.email "${{ github.event.inputs.email || 'rakkaevandra@gmail.com' }}"
          git config user.name "${{ github.event.inputs.username || 'RakkaEvandra06' }}"

          git add -A

          arr[0]="chore(bot): 🥶 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 🥵 auto commit"
          arr[3]="chore(bot): 🗿 auto commit"
          arr[4]="chore(bot): 👻 auto commit"

          rand=$((RANDOM % ${#arr[@]}))

          git diff --cached --quiet || git commit -m "${arr[$rand]}"

      - name: DO It
        run: |
          LIMIT=${{ github.event.inputs.limit || 5 }}

          for ((i=0; i<=LIMIT; i++))
          do
            d="$i-$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            echo "$d" > LAST_UPDATED

            git add -A
            git commit -m "${{ github.event.inputs.commit || 'Penghijauan' }}" || true
          done

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true