name: Auto commit

on:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Commit changes
        run: |
          git config user.email "rakkaevandra@gmail.com"
          git config user.name "RakkaEvandra06"

      - name: Perform sequential commits
        run: |
          set -o pipefail

          LIMIT=5

          arr[0]="chore(bot): 🥶 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 🥵 auto commit"
          arr[3]="chore(bot): 🗿 auto commit"
          arr[4]="chore(bot): 👻 auto commit"

          for ((i=1; i<=LIMIT; i++))
          do
            rand=$((RANDOM % ${#arr[@]}))

            echo "$i-$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > LAST_UPDATED

            git add -A
            git diff --cached --quiet || git commit -m "${arr[$rand]}"
          done

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true